# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Короткий опис')),
                ('description', models.CharField(max_length=1000, verbose_name='Опис')),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('radius', models.FloatField(verbose_name='Радіус')),
                ('map_lon', models.CharField(max_length=64, verbose_name='Довгота')),
                ('map_lat', models.CharField(max_length=64, verbose_name='Широта')),
            ],
            options={
                'verbose_name_plural': 'Демографія',
                'verbose_name': 'Демографія',
                'db_table': 'region_peoples',
            },
        ),
        migrations.CreateModel(
            name='PeopleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('color', models.CharField(max_length=100, verbose_name='Назва кольору англійською')),
            ],
            options={
                'verbose_name_plural': 'Категорії',
                'verbose_name': 'категорія',
                'db_table': 'region_people_categories',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Короткий опис')),
                ('description', models.CharField(max_length=1000, verbose_name='Опис')),
                ('center_city', models.CharField(max_length=100, verbose_name='Місто(центр регіону)')),
                ('center_lon', models.CharField(max_length=64, verbose_name='Довгота')),
                ('center_lat', models.CharField(max_length=64, verbose_name='Широта')),
            ],
            options={
                'verbose_name_plural': 'Регіони',
                'verbose_name': 'регіон',
                'db_table': 'region_regions',
            },
        ),
        migrations.AddField(
            model_name='people',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.PeopleCategory', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='people',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Region', verbose_name='Регіон'),
        ),
    ]
