# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionMapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_lon', models.CharField(max_length=64, verbose_name='Довгота')),
                ('map_lat', models.CharField(max_length=64, verbose_name='Широта')),
                ('order', models.IntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_points', to='system.Region', verbose_name="Інвестиційний об'єкт")),
            ],
            options={
                'verbose_name_plural': 'Точки на мапі',
                'verbose_name': 'Точка на мапі',
                'db_table': 'region_points',
            },
        ),
    ]
