# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name_plural': 'Типи договорів',
                'verbose_name': 'Тип договору',
                'db_table': 'investmap_contract_types',
            },
        ),
        migrations.CreateModel(
            name='InvestMapLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=32)),
                ('ip_address', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Логи',
                'verbose_name': 'Лог',
                'db_table': 'investmap_logs',
            },
        ),
        migrations.CreateModel(
            name='InvestMapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_lon', models.CharField(max_length=64, verbose_name='Довгота')),
                ('map_lat', models.CharField(max_length=64, verbose_name='Широта')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Точки на мапі',
                'verbose_name': 'Точка на мапі',
                'db_table': 'investmap_points',
            },
        ),
        migrations.CreateModel(
            name='InvestmentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.CharField(max_length=1000, verbose_name='Опис')),
                ('price', models.CharField(max_length=16, verbose_name='Ціна')),
                ('metrics', models.CharField(max_length=50, verbose_name='Площа')),
                ('image', models.ImageField(upload_to='objects', verbose_name='Зображення')),
            ],
            options={
                'verbose_name_plural': "Інвестиційні об'єкти",
                'verbose_name': "інвестиційний об'єкт",
                'db_table': 'investmap_objects',
            },
        ),
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('marker_picture', models.ImageField(upload_to='categories_markers', verbose_name='Зображення маркера')),
            ],
            options={
                'verbose_name_plural': "Категорії об'єктів",
                'verbose_name': "Категорія об'єкта",
                'db_table': 'investmap_object_categories',
            },
        ),
        migrations.CreateModel(
            name='ObjectHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
                ('contacts', models.CharField(max_length=300, verbose_name='Контакти')),
                ('map_lon', models.CharField(max_length=64, verbose_name='Довгота')),
                ('map_lat', models.CharField(max_length=64, verbose_name='Широта')),
            ],
            options={
                'verbose_name_plural': 'Балансоутримувачі',
                'verbose_name': 'Балансоутримувач',
                'db_table': 'investmap_holders',
            },
        ),
        migrations.CreateModel(
            name='OwnershipForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name_plural': 'Форми власності',
                'verbose_name': 'Форма власності',
                'db_table': 'investmap_ownership_forms',
            },
        ),
        migrations.AddField(
            model_name='objectholder',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmap.OwnershipForm', verbose_name='Форма власності'),
        ),
        migrations.AddField(
            model_name='investmentobject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmap.ObjectCategory', verbose_name="Категорія об'єкта"),
        ),
        migrations.AddField(
            model_name='investmentobject',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmap.ContractType', verbose_name='Тип договору'),
        ),
        migrations.AddField(
            model_name='investmentobject',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmap.ObjectHolder', verbose_name='Власник'),
        ),
        migrations.AddField(
            model_name='investmentobject',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Region', verbose_name='Регіон'),
        ),
        migrations.AddField(
            model_name='investmappoint',
            name='investment_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_points', to='investmap.InvestmentObject', verbose_name="Інвестиційний об'єкт"),
        ),
        migrations.AddField(
            model_name='investmaplog',
            name='investmap_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investmap.InvestmentObject'),
        ),
        migrations.AddField(
            model_name='investmaplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
